### PR TITLE
wrong engine being used

### LINKED ISSUE #77: wrong engine for yarn set :(
#Bug report

## Wrong engine being set

Do not set yarn in engine to a version which doesn't exist! At the moment [1.22.4](https://classic.yarnpkg.com/en/) is latest, there is no 1.3

This makes yarn install impossible when this lib is a submodule of something else.

https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/blob/develop/package.json#L24

which will throw an error:
```
error @endemolshinegroup/cosmiconfig-typescript-loader@1.0.2: The engine "yarn" is incompatible with this module. Expected version ">=1.3.0".
error Found incompatible module
```

Its wrong since [2018](https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/commit/215cfd793eaae5dd97f8043c4275f9dab6c87c1d) maybe you meant 'npm' :)

### PR DESCRIPTION
**Pull request by maapteh**
fixes #77

```
error @endemolshinegroup/cosmiconfig-typescript-loader@1.0.2: The engine "yarn" is incompatible with this module. Expected version ">=1.3.0".
error Found incompatible module
```

### CODE REVIEW

**Comment by hassankhan** [comment]
Fixed in 09983de925080107f4a90e822b3dca6a79fc9b56

**Comment by maapteh** [comment]
No you didnt fix it
https://github.com/yarnpkg/yarn/blob/master/CHANGELOG.md

**Comment by maapteh** [comment]
@hassankhan pls check your changes, they are wrong

**Comment by hassankhan** [comment]
Hi @maapteh, 

Thanks for the update. In #77, you said the issue was that v1.3.0 does not exist. I looked through the available versions from [npmjs.com](https://www.npmjs.com/package/yarn) and picked the closest version that did exist.

**Comment by maapteh** [comment]
I also mentioned that maybe you meant NPM and not YARN

the issue happens when you use your npm library with yarn then it reads its package json and has the engine set to a yarn version which is not existing by facebook at all :)

**Comment by maapteh** [comment]
Just remove that line, what i did in my PR which you then not took over. Good luck!

**Comment by hassankhan** [comment]
Ahhh right I see now, thanks for the explanation, I hadn't even realized that it could be an issue in that way 😅 will fix up shortly 👍

**Comment by hassankhan** [comment]
Fixed in 26e9aec31b0465ab65568c1b192376c84be4fd41

**Pull request closed without merging**
