### PR TITLE
fix(package): add missing dependency "make-error"

### PR DESCRIPTION
**Pull request by elliottsj**
## What did you implement:

Add "make-error" to package.json "dependencies", so that it can be resolved by Node.js, to prevent issues like https://github.com/apollographql/apollo-tooling/issues/1070

To reproduce the original problem:

```
$ npm install --global pnpm
$ pnpm install @endemolshinegroup/cosmiconfig-typescript-loader
$ node -r '@endemolshinegroup/cosmiconfig-typescript-loader'
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'make-error'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/spencerelliott/Dev/elliottsj/cosmiconfig-test/node_modules/.registry.npmjs.org/@endemolshinegroup/cosmiconfig-typescript-loader/1.0.0/node_modules/@endemolshinegroup/cosmiconfig-typescript-loader/dist/Errors/TypeScriptCompileError.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

## How did you implement it:

Manually add it to package.json, then run `yarn` to update the lockfile.

## How can we verify it:

```
# first check out this branch, then:
$ npm run build
$ npm install --global pnpm
$ mkdir ../testdir
$ cd ../testdir
$ pnpm install ../cosmiconfig-typescript-loader/
$ node -r '@endemolshinegroup/cosmiconfig-typescript-loader'
> // no errors
```

## Tasks:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by hassankhan** [comment]
Hi @elliottsj, thanks for the PR! Quick question, this package itself doesn't make use of `make-error`, so I'm not quite sure how the error manifests.

**Comment by hassankhan** [comment]
Hi @elliottsj, thanks for the PR and for catching the bug!

**Comment by aleccool213** [comment]
@hassankhan when will this be released?

**Comment by hassankhan** [comment]
My bad, been snowed under with other projects and completely forgot about this PR.

**Pull request merged**
