### PR TITLE
fix: remove unnecessary `async` keyword

### PR DESCRIPTION
**Pull request by danielkcz**
## What did you implement:

I've removed the `async` keyword to make the loader compatible with `cosmiconfigSync()`.

## How did you implement it:

See above :)

## How can we verify it:

Try to use the plugin with `cosmiconfigSync()`.

## Tasks:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by jacksteamdev** [comment]
@FredyC ESLint [`require-await`](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/docs/rules/require-await.md) is no joke! :man_facepalming: 

If @hassankhan isn't maintaining this anymore, have you thought about publishing this on NPM?

**Comment by hassankhan** [comment]
Hi @jacksteamdev @FredyC :wave:

Unfortunately I don't have commit rights to this repo as I'm not an @endemolshinegroup employee any more. I've been meaning to fork the repo and republish it under @radicalcondor, but I didn't have a firm deadline for it 😅

**Review by hassankhan — APPROVED** [review]

**Comment by hassankhan** [comment]
Just got my commit privileges restored, thanks for the PR @FredyC :tada:

**Comment by hassankhan** [comment]
Ahh just realised that Travis CI doesn't work any more, going to need to switch over to GitHub Actions before the Ci can release a new version. I've created a new issue for that: https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/issues/185

**Pull request merged**
